#!/bin/bash

# Render Deployment Helper Script

echo "🎨 Render Deployment Guide"
echo "=========================="
echo ""

echo "📋 Step-by-Step Instructions:"
echo ""
echo "1. Push your code to GitHub:"
echo "   git add ."
echo "   git commit -m 'Ready for Render deployment'"
echo "   git push origin main"
echo ""
echo "2. Go to Render:"
echo "   https://render.com"
echo ""
echo "3. Sign up (free, no credit card needed)"
echo ""
echo "4. Create New Web Service:"
echo "   - Click 'New +' → 'Web Service'"
echo "   - Connect your GitHub account"
echo "   - Select your repository"
echo ""
echo "5. Configure:"
echo "   - Name: fraud-detection-api"
echo "   - Environment: Docker"
echo "   - Region: Choose closest to you"
echo "   - Branch: main"
echo "   - Root Directory: (leave empty)"
echo ""
echo "6. Advanced Settings (optional):"
echo "   - Auto-Deploy: Yes"
echo "   - Health Check Path: /health"
echo ""
echo "7. Click 'Create Web Service'"
echo ""
echo "8. Wait for deployment (5-10 minutes)"
echo ""
echo "9. Your app will be at:"
echo "   https://fraud-detection-api.onrender.com"
echo ""
echo "✅ Done! Your API is live!"
echo ""
echo "📊 Monitoring:"
echo "   - View logs in Render dashboard"
echo "   - Check metrics and uptime"
echo "   - Set up alerts if needed"
echo ""

